# <span style="color:red"> DATASCI 185 - Example Quiz </span>

<font size = "5">

**Note:** This "example" quiz is only intended to demonstrate how our in-class quizzes will work.

<font size = "4" >
This quiz is open book 

<br>

- You <span style="color:red"> CAN </span> use all material from the course repo

- You should <span style="color:red"> NOT </span> use other resources outside the course repo.

- You should <span style="color:red"> NOT </span> collaborate with other students

<!-- - Use of LLMs or any AI tools is <span style="color:red"> NOT ALLOWED </span> -->

- AI assistance is <span style="color:red"> NOT </span> permitted for this assignment.

- To get full credit, the code should work as intended. But try to attempt every problem - you can still receive partial credit.

<br>

Print the following string:

"I will abide by Emory's code of conduct"

In [2]:
print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

<font size = "4">

**(a)** Read in data

<font size = "3">

Import the Pandas library and read in the dataset "features_quiz.csv" using `pandas.read_csv`. Assign the resulting DataFrame to a variable named "df_quiz"

In [19]:
# Your code here
import pandas as pd
df_quiz = pd.read_csv('data/features_quiz.csv')

import math
df_quiz.describe()

              mpg   cylinders  displacement       weight  acceleration
count  398.000000  398.000000    398.000000   398.000000    398.000000
mean    23.514573    5.454774    193.427136  2970.424623     15.568090
std      7.815984    1.701004    104.268683   846.841774      2.757689
min      9.000000    3.000000     68.000000  1613.000000      8.000000
25%     17.500000    4.000000    104.250000  2223.750000     13.825000
50%     23.000000    4.000000    148.500000  2803.500000     15.500000
75%     29.000000    8.000000    262.000000  3608.000000     17.175000
max     46.600000    8.000000    455.000000  5140.000000     24.800000

In [26]:
display (df_quiz[['mpg','cylinders']])

      mpg  cylinders
0    18.0          8
1    15.0          8
2    18.0          8
3    16.0          8
4    17.0          8
..    ...        ...
393  27.0          4
394  44.0          4
395  32.0          4
396  28.0          4
397  31.0          4

[398 rows x 2 columns]

<font size = "4">

**(b)** Swap two values

<font size = "3">

Does the code below swap the values of a and b? If not, write code that does swap their values.

In [11]:
a = "left"
b = "right"

b = a

print(a)
print(b)

left
left

In [12]:
# If it doesn't work, put your changes here:
a = "left"
b = "right"

tempo = b
b = a
a = tempo
print(a)
print(b)

right
left

<font size = "4">

**(c)** Nested lists

<font size = "3">

Write code that creats a single list, called birthdays, containing all of the lists given in the cell below.

In [18]:
abed = ["Abed", "March", 23, 2007]
britta = ["Britta", "July", 14, 1998]
jeff = ["Jeff", "December", 8, 1990]
shirley = ["Shirley", "January", 19, 1990]
annie = ["Annie", "September", 27, 2007]
troy = ["Troy", "June", 5, 2007]
pierce = ["Pierce", "December", 30, 1962]


birthdays = abed, britta, jeff, shirley, annie, troy, pierce
print(birthdays)
## Your code here:

(['Abed', 'March', 23, 2007], ['Britta', 'July', 14, 1998], ['Jeff', 'December', 8, 1990], ['Shirley', 'January', 19, 1990], ['Annie', 'September', 27, 2007], ['Troy', 'June', 5, 2007], ['Pierce', 'December', 30, 1962])